### ISSUE TITLE
Unsubscribe from all interests

### ISSUE THREAD

**Issue by Rhysjc** [pusher/pusher-websocket-android#27]
Is there any way we can unsubscribe from ALL interests, rather than a specific one?

**Comment by StevePotter** [comment]
+1  @Rhysjc I looked into the library and it's not possible.  They would need to add a new REST API endpoint with a method that calls it.  Pusher, what's the deal here?  We need this

**Comment by blastering66** [comment]
Yes We NEED THIS !!!

even in android, i unsubscribed an interest, but still got the notifications

**Comment by zmarkan** [comment]
I think it should be doable by tracking subs in the client, and subscribing one by one. I'm not sure whether the backend supports bulk unsubscribes at the moment. 

@blastering66 I think your problem is with the unsubscribing from a _single_ interest, right? This issue is for unsubscribing from all interests that a user currently has. Can you please either create a new issue here in github for that or open a support ticket here and I can look into it for you: https://support.pusher.com/hc/en-us/requests/new

Thanks

**Comment by kn100** [comment]
Closing due to age

**Comment by StevePotter** [comment]
@kn100 it's old because nobody from Pusher ever responded.  Can anything be done about this?  It's still relevant to us.

**Comment by kn100** [comment]
Hi, 

I'm sorry for the slow response! I'll look into this tomorrow.

**Comment by kn100** [comment]
In fact, reading into this, we have actually done a load of work on a new, much better implementation of push notifications! You can check it out at https://pusher.com/beams - this is where our active development effort is focussed for the moment.
